name = "ormi-api"
account_id = "475a121e52d9057d0e99c52062f3b6e5"
compatibility_date = "2023-09-04"
main = "dist/worker-server.js"

# Node.js compatibility flags
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
NODE_ENV = "production"
ENVIRONMENT = "production"
SUPABASE_URL = "https://kmhmgutrhkzjnsgifsrl.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttaG1ndXRyaGt6am5zZ2lmc3JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MDYwNTYsImV4cCI6MjA2NzA4MjA1Nn0.Yeg2TBq3K9jddh-LQFHadr1rv_GaYS-SBVTfnZS6z3c"
R2_PUBLIC_URL = "https://cdn.ormi.com"

# Workers Logs configuration
[observability]
enabled = true

[observability.logs]
invocation_logs = true
head_sampling_rate = 1.0

# Define the build process
[build]
command = "npm run build"

# Routes configuration
[[routes]]
pattern = "api.ormi.com/*"
zone_name = "ormi.com"

# R2 Storage configuration - Fixed binding name
[[r2_buckets]]
binding = "R2_BUCKET_NAME"
bucket_name = "ormi-storage"
preview_bucket_name = "ormi-storage-dev"

# R2 Public URL configuration
[[routes]]
pattern = "data.ormi.com/*"
zone_name = "ormi.com"

# Environment-specific settings
[env.production]
name = "ormi-api"
log_level = "warn"
workers_dev = false

[env.production.vars]
NODE_ENV = "production"
ENVIRONMENT = "production"

[env.staging]
name = "ormi-api-staging"
workers_dev = true
routes = []

[env.development]
name = "ormi-api-dev"
workers_dev = true
routes = []

[env.development.vars]
NODE_ENV = "development"
SUPABASE_URL = "https://kmhmgutrhkzjnsgifsrl.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttaG1ndXRyaGt6am5zZ2lmc3JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MDYwNTYsImV4cCI6MjA2NzA4MjA1Nn0.Yeg2TBq3K9jddh-LQFHadr1rv_GaYS-SBVTfnZS6z3c"

# Secrets are managed using `wrangler secret put` command
# Required secrets:
# - DATABASE_URL: Supabase database URL 