name = "ormi-api"
account_id = "475a121e52d9057d0e99c52062f3b6e5"
compatibility_date = "2023-09-04"
main = "dist/worker-server.js"

# Node.js compatibility flags
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
NODE_ENV = "production"
ENVIRONMENT = "production"

# Workers Logs configuration
[observability]
enabled = true

[observability.logs]
invocation_logs = true
head_sampling_rate = 1.0

# Define the build process
[build]
command = "npm run build"

# Routes configuration
[[routes]]
pattern = "api.ormi.com/*"
zone_name = "ormi.com"

# Environment-specific settings
[env.production]
name = "ormi-api"
log_level = "warn"
workers_dev = false

[env.production.vars]
NODE_ENV = "production"
ENVIRONMENT = "production"

[env.staging]
name = "ormi-api-staging"
workers_dev = true
routes = []

[env.development]
name = "ormi-api-dev"
workers_dev = true
routes = []
vars = { NODE_ENV = "development" }

# Secrets are managed using `wrangler secret put` command
# Required secrets:
# - DATABASE_URL: Supabase database URL 